setting_configs = {
    'default': {
        'in_channels_controlnet': 4,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 4,
        'preprocessor': "lineart_anime",
    },
    'v00-naive-unet-edit2-raw2-refnet-ref1-unet-edit2-raw2-refnet-ref1': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 8,
        'preprocessor': None,
    },
    'v01-lineart-unet-edit2-raw2-edge2-refnet-ref1-unet-edit2-raw2-edge2-refnet-ref1': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 12,
        'preprocessor': 'lineart',
    },
    'v02-lineart-unet-edit2-edge2-refnet-ref1': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 8,
        'preprocessor': 'lineart',
    },
    'v03-lineart-unet-edit2-raw2-edge2-refnet-ref1-edge1': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 8,
        'in_channels_denoising_unet': 12,
        'preprocessor': 'lineart',
    },
    'v04-lineart-unet-edit2-edge2-refnet-ref1-edge1': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 8,
        'in_channels_denoising_unet': 8,
        'preprocessor': 'lineart',
    },
    'v05-lineart-unet-edit2-refnet-ref1-edge1-edge2': {
        'in_channels_controlnet': None,
        'in_channels_reference_unet': 12,
        'in_channels_denoising_unet': 4,
        'preprocessor': 'lineart',
    },
    'v06-lineart-unet-edit2-refnet-ref1-controlnet-lineart-edge2': {
        'in_channels_controlnet': 4,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 4,
        'preprocessor': 'lineart',
    },
    'v06-lineart_anime-unet-edit2-refnet-ref1-controlnet-lineart-edge2': {
        'in_channels_controlnet': 4,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 4,
        'preprocessor': 'lineart',
    },
    'v07-lineart-unet-edit2-refnet-ref1-edge1-controlnet-lineart-edge2': {
        'in_channels_controlnet': 4,
        'in_channels_reference_unet': 8,
        'in_channels_denoising_unet': 4,
        'preprocessor': 'lineart',
    },
    'v08-naive-unet-edit2-refnet-ref1-controlnet-ip2p-raw2': {
        'in_channels_controlnet': 4,
        'in_channels_reference_unet': 4,
        'in_channels_denoising_unet': 4,
        'preprocessor': None,
    },
    # 'v09-lineart-unet-dual-edit2-edge2-refnet-ref1-edge1-controlnet-ip2p-raw2-edge2': {
    #     'in_channels_controlnet': 8,
    #     'in_channels_reference_unet': 8,
    #     'in_channels_denoising_unet': 8,
    #     'preprocessor': 'lineart',
    # },
    # 'v10-lineart-unet-dual-edit2-edge2-refnet-ref1-edge1-controlnet-lineart-raw2-edge2': {
    #     'in_channels_controlnet': 8,
    #     'in_channels_reference_unet': 8,
    #     'in_channels_denoising_unet': 8,
    #     'preprocessor': 'lineart',
    # },
    # 'v10-lineart-unet-dual-edit2-edge2-refnet-ref1-controlnet-raw2': {
    #     'in_channels_controlnet': 8,
    #     'in_channels_reference_unet': 4,
    #     'in_channels_denoising_unet': 4,
    #     'preprocessor': 'lineart',
    # },
    # 'v11-lineart-unet-dual-edit2-edge2-refnet-ref1-edge1-controlnet-raw2': {
    #     'in_channels_controlnet': 8,
    #     'in_channels_reference_unet': 8,
    #     'in_channels_denoising_unet': 4,
    #     'preprocessor': 'lineart',
    # },
    # 'v12-lineart-unet-dual-edit2-edge2-refnet-ref1-controlnet-raw2-edge2': {
    #     'in_channels_controlnet': 8,
    #     'in_channels_reference_unet': 4,
    #     'in_channels_denoising_unet': 8,
    #     'preprocessor': 'lineart',
    # },
}